apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-test
  namespace: test
  labels:
    app: docker-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker-test
  template:
    metadata:
      labels:
        app: docker-test
    spec:
      containers:
        - name: docker-test
          image: <DOCKERHUB_USERNAME>/docker-test:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "50Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
