apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-test
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker-test
  template:
    metadata:
      labels:
        app: docker-test
    spec:
      containers:
      - name: docker-test
        image: ashwinjoeoffl/docker-test:latest  # This will be replaced by GitHub Actions
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "50Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: docker-test
  namespace: test
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8080
  selector:
    app: docker-test