apiVersion: v1
kind: Service
metadata:
  name: docker-test
  namespace: test
spec:
  selector:
    app: docker-test
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8080
  type: LoadBalancer
